import jsPDF from "jspdf";
import letterhead from "../assets/letterhead.png";
import { useBusinessData } from "../context/BusinessDataContext";




export const generateInvoicePDF = (selectedSale) => {
    if (!selectedSale) return;

    const doc = new jsPDF();
    const formatCurrency = (value) => `Rs${Number(value || 0).toFixed(2)}`;
    const formatDate = (value) => {
      if (!value) return "-";
      const date = new Date(value);
      if (Number.isNaN(date.getTime())) return "-";
      const day = String(date.getDate()).padStart(2, "0");
      const month = String(date.getMonth() + 1).padStart(2, "0");
      const year = date.getFullYear();
      return `${day}/${month}/${year}`;
    };

    const rows = [
      ["Company", selectedSale.companyName || "-"],
      ["Product", selectedSale.productName || "-"],
      ["Quantity", String(selectedSale.quantity || 0)],
      ["Rate", formatCurrency(selectedSale.rate)],
      ["Total Price", formatCurrency(selectedSale.totalPrice)],
      ["Final Amount", formatCurrency(selectedSale.finalAmount)],
      ["Date", formatDate(selectedSale.date)],
    ];

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const leftX = 20;
    const rightX = pageWidth - 20;
    const labelX = 22;
    const valueX = pageWidth - 22;
    const imageX = 10;
    const imageY = 10;
    const imageWidth = pageWidth - 20;
    const imageProps = doc.getImageProperties(letterhead);
    const imageHeight = (imageProps.height * imageWidth) / imageProps.width;
    const separatorY = imageY + imageHeight + 4;
    const rowStartY = 85;
    const rowHeight = 12;

    doc.addImage(letterhead, "PNG", imageX, imageY, imageWidth, imageHeight);
    doc.setDrawColor(180, 180, 180);
  

    const invoiceID = "INV-" + (selectedSale._id || "").slice(-6);
    const displayDate = formatDate(selectedSale.date);
    const metaY = 48;

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`Invoice ID: ${invoiceID}`, 15, metaY);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Date: ${displayDate}`, pageWidth - 15, metaY, { align: "right" });

    doc.setDrawColor(180, 180, 180);
    doc.line(10, 55, pageWidth - 10, 55);

    doc.setFontSize(19);
    doc.setFont("helvetica", "bold");
    doc.text("Invoice", pageWidth / 2, 70, { align: "center" });
 doc.setFillColor(255, 193, 7);

doc.roundedRect(145, 62, 40, 10, 3, 3, "F");

doc.setTextColor(0, 0, 0);
doc.setFontSize(11);
doc.setFont("helvetica", "bold");

doc.text(
  selectedSale.status?.toUpperCase() || "UNPAID",
  165,
  69,
  { align: "center" }
);

doc.setTextColor(0, 0, 0);

    doc.setFontSize(12);
    rows.forEach((row, index) => {
      const y = rowStartY + index * rowHeight;

      doc.setFont("helvetica", "bold");
      doc.text(row[0], labelX, y);

      doc.setFont("helvetica", "normal");
      doc.text(row[1], valueX, y, { align: "right" });
      
      if (index < rows.length - 1) {
        doc.setDrawColor(225, 225, 225);
        doc.line(leftX, y + 3, rightX, y + 3);
      }
    });

    doc.line(leftX, rowStartY + rows.length * rowHeight - 1, rightX, rowStartY + rows.length * rowHeight - 1);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by IBOP", pageWidth / 2, pageHeight - 10, { align: "center" });

    doc.save(`invoice-${selectedSale._id || "sale"}.pdf`);
  };
